"""add personal_profiles and profile_log_entries

Revision ID: 1d49a862cc7f
Revises: 5b766a96b2a4
Create Date: 2026-09-15 13:25:18.183170
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '1d49a862cc7f'
down_revision: Union[str, None] = '5b766a96b2a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Contrat lu par réflexion par Alembic (cf. `script.py.mako`), jamais référencé ici.
__all__ = ["revision", "down_revision", "branch_labels", "depends_on", "upgrade", "downgrade"]


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('personal_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organisation_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('emergency_contact', sa.String(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('personal_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_personal_profiles_organisation_id'), ['organisation_id'], unique=False)

    op.create_table('profile_log_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['personal_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('profile_log_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_profile_log_entries_profile_id'), ['profile_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile_log_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_profile_log_entries_profile_id'))

    op.drop_table('profile_log_entries')
    with op.batch_alter_table('personal_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_personal_profiles_organisation_id'))

    op.drop_table('personal_profiles')
    # ### end Alembic commands ###
