"""admin action log

Revision ID: 2fde0831cb40
Revises: f6a7b8c9d0e1
Create Date: 2026-08-06 22:43:36.572020
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '2fde0831cb40'
down_revision: Union[str, None] = 'a107b77b53e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Contrat lu par réflexion par Alembic (cf. `script.py.mako`), jamais référencé ici.
__all__ = ["revision", "down_revision", "branch_labels", "depends_on", "upgrade", "downgrade"]


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_action_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('admin_action_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_admin_action_log_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_admin_action_log_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_admin_action_log_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin_action_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_admin_action_log_user_id'))
        batch_op.drop_index(batch_op.f('ix_admin_action_log_created_at'))
        batch_op.drop_index(batch_op.f('ix_admin_action_log_action'))

    op.drop_table('admin_action_log')
    # ### end Alembic commands ###
