"""add users.session_epoch

Revision ID: 34c8fcbd58c0
Revises: 44ee815735fc
Create Date: 2026-07-31 15:27:03.189645
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '34c8fcbd58c0'
down_revision: Union[str, None] = '44ee815735fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # `server_default="0"` allows adding NOT NULL to an existing table without
    # touching the rows first (production migrations run against an empty table
    # today, but this keeps the migration idempotent-safe).
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'session_epoch',
                sa.Integer(),
                nullable=False,
                server_default='0',
            )
        )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('session_epoch')

    # ### end Alembic commands ###
