"""retient l'identité des épreuves absorbées par une fusion (#983)

Revision ID: 4d95313cbf07
Revises: daf0d7d41178
Create Date: 2026-09-29 16:12:39.357825
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '4d95313cbf07'
down_revision: Union[str, None] = 'daf0d7d41178'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Contrat lu par réflexion par Alembic (cf. `script.py.mako`), jamais référencé ici.
__all__ = ["revision", "down_revision", "branch_labels", "depends_on", "upgrade", "downgrade"]


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('absorbed_courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_course_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=True),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('is_relay', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['target_course_id'], ['courses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('absorbed_courses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_absorbed_courses_target_course_id'), ['target_course_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_absorbed_courses_url'), ['url'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('absorbed_courses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_absorbed_courses_url'))
        batch_op.drop_index(batch_op.f('ix_absorbed_courses_target_course_id'))

    op.drop_table('absorbed_courses')
    # ### end Alembic commands ###
