"""supprime la table volunteer_declarations

Revision ID: 5b766a96b2a4
Revises: b8a572868051
Create Date: 2026-09-01 16:52:51.072068
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '5b766a96b2a4'
down_revision: Union[str, None] = 'b8a572868051'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Contrat lu par réflexion par Alembic (cf. `script.py.mako`), jamais référencé ici.
__all__ = ["revision", "down_revision", "branch_labels", "depends_on", "upgrade", "downgrade"]


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('volunteer_declarations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_volunteer_declarations_beneficiary_user_id'))

    op.drop_table('volunteer_declarations')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('volunteer_declarations',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=False),
    sa.Column('beneficiary_user_id', sa.INTEGER(), nullable=False),
    sa.Column('author_user_id', sa.INTEGER(), nullable=False),
    sa.Column('status', sa.VARCHAR(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['author_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['beneficiary_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('volunteer_declarations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_volunteer_declarations_beneficiary_user_id'), ['beneficiary_user_id'], unique=False)

    # ### end Alembic commands ###
