"""participation_validation_timestamps

Revision ID: 611d55721316
Revises: 05de2237111f
Create Date: 2026-08-26 13:01:42.008432
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '611d55721316'
down_revision: Union[str, None] = '05de2237111f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Contrat lu par réflexion par Alembic (cf. `script.py.mako`), jamais référencé ici.
__all__ = ["revision", "down_revision", "branch_labels", "depends_on", "upgrade", "downgrade"]


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('participations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('validated_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('rejected_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('participations', schema=None) as batch_op:
        batch_op.drop_column('rejected_at')
        batch_op.drop_column('validated_at')

    # ### end Alembic commands ###
