"""add participation is_relay

Revision ID: 723259e01cdd
Revises: e734b8c5c962
Create Date: 2026-06-15 22:04:02.010810
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '723259e01cdd'
down_revision: Union[str, None] = 'e734b8c5c962'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('participations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_relay', sa.Boolean(), server_default='false', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('participations', schema=None) as batch_op:
        batch_op.drop_column('is_relay')

    # ### end Alembic commands ###
