"""add user_feedback table

Revision ID: 9427c6c5e84a
Revises: b3c4d5e6f7a8
Create Date: 2026-08-12 19:56:44.074156
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '9427c6c5e84a'
down_revision: Union[str, None] = 'b3c4d5e6f7a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Contrat lu par réflexion par Alembic (cf. `script.py.mako`), jamais référencé ici.
__all__ = ["revision", "down_revision", "branch_labels", "depends_on", "upgrade", "downgrade"]


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('page_url', sa.String(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('github_url', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user_feedback', schema=None) as batch_op:
        batch_op.create_index('ix_user_feedback_ip_address_created_at', ['ip_address', 'created_at'], unique=False)
        batch_op.create_index('ix_user_feedback_status_created_at', ['status', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_feedback_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_feedback', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_feedback_user_id'))
        batch_op.drop_index('ix_user_feedback_status_created_at')
        batch_op.drop_index('ix_user_feedback_ip_address_created_at')

    op.drop_table('user_feedback')
    # ### end Alembic commands ###
