"""declared_by_user_id nullable sur volunteer_actions

Revision ID: b8a572868051
Revises: d3efd9d4d908
Create Date: 2026-09-01 14:21:49.867201
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'b8a572868051'
down_revision: Union[str, None] = 'd3efd9d4d908'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Contrat lu par réflexion par Alembic (cf. `script.py.mako`), jamais référencé ici.
__all__ = ["revision", "down_revision", "branch_labels", "depends_on", "upgrade", "downgrade"]


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('volunteer_actions', schema=None) as batch_op:
        batch_op.alter_column('declared_by_user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('volunteer_actions', schema=None) as batch_op:
        batch_op.alter_column('declared_by_user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
