"""ajoute la table participation_teammates : équipiers d'un relais attribué (#894)

Revision ID: c10f3d7ae85e
Revises: 5b766a96b2a4
Create Date: 2026-09-24 17:33:39.824318
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'c10f3d7ae85e'
down_revision: Union[str, None] = '5b766a96b2a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Contrat lu par réflexion par Alembic (cf. `script.py.mako`), jamais référencé ici.
__all__ = ["revision", "down_revision", "branch_labels", "depends_on", "upgrade", "downgrade"]


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('participation_teammates',
    sa.Column('participation_id', sa.Integer(), nullable=False),
    sa.Column('athlete_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['athlete_id'], ['athletes.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['participation_id'], ['participations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('participation_id', 'athlete_id')
    )
    with op.batch_alter_table('participation_teammates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_participation_teammates_athlete_id'), ['athlete_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('participation_teammates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_participation_teammates_athlete_id'))

    op.drop_table('participation_teammates')
    # ### end Alembic commands ###
