"""add volunteer_declarations table

Revision ID: c75d1532feb2
Revises: 3368b16a21e6
Create Date: 2026-08-30 16:45:25.814527
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'c75d1532feb2'
down_revision: Union[str, None] = '3368b16a21e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Contrat lu par réflexion par Alembic (cf. `script.py.mako`), jamais référencé ici.
__all__ = ["revision", "down_revision", "branch_labels", "depends_on", "upgrade", "downgrade"]


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('volunteer_declarations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('beneficiary_user_id', sa.Integer(), nullable=False),
    sa.Column('author_user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['author_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['beneficiary_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('volunteer_declarations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_volunteer_declarations_beneficiary_user_id'), ['beneficiary_user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('volunteer_declarations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_volunteer_declarations_beneficiary_user_id'))

    op.drop_table('volunteer_declarations')
    # ### end Alembic commands ###
