"""add title description status to volunteer actions

Revision ID: d3efd9d4d908
Revises: c75d1532feb2
Create Date: 2026-08-31 16:22:25.244791
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'd3efd9d4d908'
down_revision: Union[str, None] = 'c75d1532feb2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Contrat lu par réflexion par Alembic (cf. `script.py.mako`), jamais référencé ici.
__all__ = ["revision", "down_revision", "branch_labels", "depends_on", "upgrade", "downgrade"]


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('volunteer_actions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(), server_default='en_attente', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('volunteer_actions', schema=None) as batch_op:
        batch_op.drop_column('status')
        batch_op.drop_column('description')
        batch_op.drop_column('title')

    # ### end Alembic commands ###
