"""add entrainements jeunes

Revision ID: e3649cbee16c
Revises: 1d49a862cc7f
Create Date: 2026-09-15 13:31:31.258967
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e3649cbee16c'
# Rebasée sur 1d49a862cc7f (#867, personal_profiles) après merge de
# epic/863-jeunes : les deux migrations partaient de 5b766a96b2a4 en parallèle
# (deux têtes Alembic). Cette révision n'était pas encore mergée ailleurs au
# moment du rebase, donc réécrite en place plutôt que doublée d'une migration
# de fusion vide.
down_revision: Union[str, None] = '1d49a862cc7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Contrat lu par réflexion par Alembic (cf. `script.py.mako`), jamais référencé ici.
__all__ = ["revision", "down_revision", "branch_labels", "depends_on", "upgrade", "downgrade"]


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entrainements_jeunes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('heure_debut', sa.Time(), nullable=True),
    sa.Column('lieu', sa.String(), nullable=True),
    sa.Column('type_seance', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('entrainement_participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entrainement_id', sa.Integer(), nullable=False),
    sa.Column('jeune_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['entrainement_id'], ['entrainements_jeunes.id'], ),
    # `personal_profiles` (#867) est désormais en base avant cette révision
    # (rebasée sur 1d49a862cc7f) : la contrainte est posée directement plutôt
    # que par une migration de suivi — cf. `research.md` §Dépendance sur le
    # profil jeune, résolue par ce rebase.
    sa.ForeignKeyConstraint(['jeune_id'], ['personal_profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('entrainement_id', 'jeune_id', name='uq_entrainement_participant')
    )
    with op.batch_alter_table('entrainement_participants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_entrainement_participants_entrainement_id'), ['entrainement_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_entrainement_participants_jeune_id'), ['jeune_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entrainement_participants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_entrainement_participants_jeune_id'))
        batch_op.drop_index(batch_op.f('ix_entrainement_participants_entrainement_id'))

    op.drop_table('entrainement_participants')
    op.drop_table('entrainements_jeunes')
    # ### end Alembic commands ###
