"""add training sessions

Revision ID: e3649cbee16c
Revises: 1d49a862cc7f
Create Date: 2026-09-15 13:31:31.258967
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e3649cbee16c'
# Rebasée sur 1d49a862cc7f (#867, personal_profiles) après merge de
# epic/863-jeunes : les deux migrations partaient de 5b766a96b2a4 en parallèle
# (deux têtes Alembic). Cette révision n'était pas encore mergée ailleurs au
# moment du rebase, donc réécrite en place plutôt que doublée d'une migration
# de fusion vide.
# Tables et colonnes renommées en place, sans « jeune » (revue de la PR #876),
# pour la même raison : aucune base partagée n'avait encore appliqué la révision.
down_revision: Union[str, None] = '1d49a862cc7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Contrat lu par réflexion par Alembic (cf. `script.py.mako`), jamais référencé ici.
__all__ = ["revision", "down_revision", "branch_labels", "depends_on", "upgrade", "downgrade"]


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('training_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('session_type', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('training_participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('training_session_id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['training_session_id'], ['training_sessions.id'], ),
    # `personal_profiles` (#867) est désormais en base avant cette révision
    # (rebasée sur 1d49a862cc7f) : la contrainte est posée directement plutôt
    # que par une migration de suivi — cf. `research.md` §Dépendance sur le
    # profil jeune, résolue par ce rebase.
    sa.ForeignKeyConstraint(['profile_id'], ['personal_profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('training_session_id', 'profile_id', name='uq_training_participant')
    )
    with op.batch_alter_table('training_participants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_training_participants_training_session_id'), ['training_session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_training_participants_profile_id'), ['profile_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('training_participants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_training_participants_profile_id'))
        batch_op.drop_index(batch_op.f('ix_training_participants_training_session_id'))

    op.drop_table('training_participants')
    op.drop_table('training_sessions')
    # ### end Alembic commands ###
