"""add appel presence jeunes

Revision ID: f4f2e5d3e9dd
Revises: e3649cbee16c
Create Date: 2026-09-15 14:30:00.716654
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'f4f2e5d3e9dd'
down_revision: Union[str, None] = 'e3649cbee16c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

# Contrat lu par réflexion par Alembic (cf. `script.py.mako`), jamais référencé ici.
__all__ = ["revision", "down_revision", "branch_labels", "depends_on", "upgrade", "downgrade"]


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entrainement_participants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('present', sa.Boolean(), nullable=True))

    with op.batch_alter_table('entrainements_jeunes', schema=None) as batch_op:
        # `server_default=""` : sans lui, une séance déjà en base violerait
        # la contrainte `NOT NULL` à l'ajout de la colonne (patron déjà
        # établi par `05094fea3bc2_manual_result_validation.py` pour
        # `is_pending_validation`).
        batch_op.add_column(sa.Column('note', sa.Text(), server_default='', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entrainements_jeunes', schema=None) as batch_op:
        batch_op.drop_column('note')

    with op.batch_alter_table('entrainement_participants', schema=None) as batch_op:
        batch_op.drop_column('present')

    # ### end Alembic commands ###
